language: php
before_script:
   - composer install
   - gem install mailcatcher
   # Temporary workaround for https://github.com/sj26/mailcatcher/issues/182
   - mailcatcher -f > out.txt&
php:
  - 5.3
