language: php
before_script:
   - composer install
   # see https://github.com/sj26/mailcatcher/issues/277
   - gem install mime-types --version "< 3"
   - gem install mailcatcher
   # Temporary workaround for https://github.com/sj26/mailcatcher/issues/182
   - mailcatcher -f > out.txt&
php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - 7.0
